rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  ProcedureSyntax,
  OrganizeImports,
  ExplicitResultTypes,
  RemoveUnused
]

OrganizeImports {
  blankLines = Auto
  coalesceImporteeSymbols = true
  expandRelative = false
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Merge
  groups = [
    "re:javax?\\.",
    "scala.",
    "*"
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = DEFAULT
  removeUnused = true
}

DisableSyntax {
  noVars = true
  noThrows = true
  noNulls = true
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = false
  noIsInstanceOf = false
  noXml = true
  noDefaultArgs = false
  noFinalize = true
}

ExplicitResultTypes {
  memberKind = [Def, Val, Var]
  memberVisibility = [Public, Protected]
  skipSimpleDefinitions = ["Lit", "Term.New"]
}

RemoveUnused {
  imports = false
  privates = true
  locals = true
  patternvars = true
  params = true
}
